
service: ops-portal-backend
app: myapp-dev
tenant: brcornelius
provider:
  name: aws
  runtime: nodejs8.10
  environment:
    POSTGRES_URL: 'postgres://dyjryrzj:G8IrVdEDMYJ3-Ix3xdnzpGUw-oVs9dCJ@baasu.db.elephantsql.com:5432/dyjryrzj'
functions:
  graphql:
    handler: handler.test
    events:
      - http:
          method: get
          path: graphql
          cors: true
          # request:
          #   parameters:
          #     id: int