
service: ops-portal-backend
app: myapp-dev
tenant: brcornelius
provider:
  name: aws
  runtime: nodejs8.10
  environment:
    POSTGRES_URL: '!!!!SEE EMAIL!!!!'
functions:
  graphql:
    handler: handler.test
    events:
      - http:
          method: get
          path: graphql
          cors: true
          # request:
          #   parameters:
          #     id: int